# Generated by Django 4.0.4 on 2022-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='modificacion',
            field=models.DateField(),
        ),
    ]
