# Generated by Django 4.0.4 on 2022-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0002_alter_entrada_modificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bebidas')),
                ('modificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlatoPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='platos')),
                ('modificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='postres')),
                ('modificacion', models.DateField()),
            ],
        ),
    ]
