# Generated by Django 4.0.5 on 2022-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0004_rename_platoprincipal_plato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
