# Generated by Django 4.0.4 on 2022-08-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_menu', '0006_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
